### PR TITLE
Bump sync spec status to candidate, add corresponding news item

### PR DESCRIPTION
**Pull request by sgwilym**

### CODE REVIEW

**Comment by AljoschaMeyer** [comment]
Lgtm. Perhaps a second paragraph stating the conditions for promoting to stable?

**Comment by sgwilym** [comment]
CleanShot 2024-06-19 at 16 07 42@2x

But that's what our wonderful cross-referencing system is for, no?!

**Comment by AljoschaMeyer** [comment]
I was thinking about the much more concrete "security-audit of the rust impl". But anyways, not important.

**Comment by sgwilym** [comment]
Sorry, misread. I understand what you're saying, but I also don't want to tie our hands with concrete conditions for upgrading statuses.

**Pull request merged**
